version: '3'
services:
  wordpress:
    image: wordpress
    environment:
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_HOST=db
    depends_on:
      - db
    networks: 
      - docker-compose-exercise2

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    networks: 
      - docker-compose-exercise2

  loadbalancer-nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - wordpress
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - docker-compose-exercise2
      
networks:
  docker-compose-exercise2: